# Importing Libraries

In [15]:
import numpy as np 
import pandas as pd 
import matplotlib.pyplot as plt 

In [55]:
df=pd.read_csv("E:/tuts/Machine Learning A-Z Udemy Template Folder/Part 1 - Data Preprocessing/Data.csv")

df.head(10)

In [38]:
df.shape

(10, 4)

In [56]:
df.head()

Country   Age   Salary Purchased
0   France  44.0  72000.0        No
1    Spain  27.0  48000.0       Yes
2  Germany  30.0  54000.0        No
3    Spain  38.0  61000.0        No
4  Germany  40.0      NaN       Yes

# Handling Missing values

In [57]:
from sklearn.preprocessing import Imputer

In [58]:
imputer=Imputer(missing_values ="NaN",strategy ='mean',axis=0)

In [59]:
imputer=imputer.fit(df.iloc[:,1:3])

In [60]:
df.iloc[:,1:3]=imputer.transform(df.iloc[:,1:3])

In [61]:
df

Country        Age        Salary Purchased
0   France  44.000000  72000.000000        No
1    Spain  27.000000  48000.000000       Yes
2  Germany  30.000000  54000.000000        No
3    Spain  38.000000  61000.000000        No
4  Germany  40.000000  63777.777778       Yes
5   France  35.000000  58000.000000       Yes
6    Spain  38.777778  52000.000000        No
7   France  48.000000  79000.000000       Yes
8  Germany  50.000000  83000.000000        No
9   France  37.000000  67000.000000       Yes

In [104]:
x=df.iloc[:,:3].values
y=df.iloc[:,-1].values

In [105]:
x

array([['France', 44.0, 72000.0],
       ['Spain', 27.0, 48000.0],
       ['Germany', 30.0, 54000.0],
       ['Spain', 38.0, 61000.0],
       ['Germany', 40.0, 63777.77777777778],
       ['France', 35.0, 58000.0],
       ['Spain', 38.77777777777778, 52000.0],
       ['France', 48.0, 79000.0],
       ['Germany', 50.0, 83000.0],
       ['France', 37.0, 67000.0]], dtype=object)

In [106]:
y

array(['No', 'Yes', 'No', 'No', 'Yes', 'Yes', 'No', 'Yes', 'No', 'Yes'],
      dtype=object)

# Handling Categorical Feature

In [107]:
from sklearn.preprocessing import LabelEncoder

In [108]:
x[:,0]=LabelEncoder().fit_transform(x[:,0])

In [109]:
x

array([[0, 44.0, 72000.0],
       [2, 27.0, 48000.0],
       [1, 30.0, 54000.0],
       [2, 38.0, 61000.0],
       [1, 40.0, 63777.77777777778],
       [0, 35.0, 58000.0],
       [2, 38.77777777777778, 52000.0],
       [0, 48.0, 79000.0],
       [1, 50.0, 83000.0],
       [0, 37.0, 67000.0]], dtype=object)

In [110]:
y=LabelEncoder().fit_transform(y)

In [111]:
y

array([0, 1, 0, 0, 1, 1, 0, 1, 0, 1])

In [112]:
from sklearn.preprocessing import OneHotEncoder

In [113]:
x=OneHotEncoder(categorical_features=[0]).fit_transform(x).toarray()

C:\Users\Chirag M. Sidhdhapur\Anaconda3\lib\site-packages\sklearn\preprocessing\_encoders.py:415: FutureWarning: The handling of integer data will change in version 0.22. Currently, the categories are determined based on the range [0, max(values)], while in the future they will be determined based on the unique values.
If you want the future behaviour and silence this warning, you can specify "categories='auto'".
In case you used a LabelEncoder before this OneHotEncoder to convert the categories to integers, then you can now use the OneHotEncoder directly.
  warnings.warn(msg, FutureWarning)


In [88]:
x_df=pd.DataFrame(x)

In [89]:
x_df

0    1    2    3          4             5
0  0.0  1.0  0.0  0.0  44.000000  72000.000000
1  1.0  0.0  0.0  1.0  27.000000  48000.000000
2  1.0  0.0  1.0  0.0  30.000000  54000.000000
3  1.0  0.0  0.0  1.0  38.000000  61000.000000
4  1.0  0.0  1.0  0.0  40.000000  63777.777778
5  0.0  1.0  0.0  0.0  35.000000  58000.000000
6  1.0  0.0  0.0  1.0  38.777778  52000.000000
7  0.0  1.0  0.0  0.0  48.000000  79000.000000
8  1.0  0.0  1.0  0.0  50.000000  83000.000000
9  0.0  1.0  0.0  0.0  37.000000  67000.000000

# Splitting Training And Testing Data

In [114]:
from sklearn.model_selection import train_test_split

In [115]:
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2,random_state=0)

In [116]:
x_train

array([[0.00000000e+00, 1.00000000e+00, 0.00000000e+00, 4.00000000e+01,
        6.37777778e+04],
       [1.00000000e+00, 0.00000000e+00, 0.00000000e+00, 3.70000000e+01,
        6.70000000e+04],
       [0.00000000e+00, 0.00000000e+00, 1.00000000e+00, 2.70000000e+01,
        4.80000000e+04],
       [0.00000000e+00, 0.00000000e+00, 1.00000000e+00, 3.87777778e+01,
        5.20000000e+04],
       [1.00000000e+00, 0.00000000e+00, 0.00000000e+00, 4.80000000e+01,
        7.90000000e+04],
       [0.00000000e+00, 0.00000000e+00, 1.00000000e+00, 3.80000000e+01,
        6.10000000e+04],
       [1.00000000e+00, 0.00000000e+00, 0.00000000e+00, 4.40000000e+01,
        7.20000000e+04],
       [1.00000000e+00, 0.00000000e+00, 0.00000000e+00, 3.50000000e+01,
        5.80000000e+04]])

In [117]:
x_test

array([[0.0e+00, 1.0e+00, 0.0e+00, 3.0e+01, 5.4e+04],
       [0.0e+00, 1.0e+00, 0.0e+00, 5.0e+01, 8.3e+04]])

In [118]:
y_train

array([1, 1, 1, 0, 1, 0, 0, 1])

In [120]:
y_test

array([0, 0])

# Feature Scalling

In [121]:
from sklearn.preprocessing import StandardScaler

In [122]:
scaler=StandardScaler()

In [123]:
x_train=scaler.fit_transform(x_train) #we need to fit first and then transform for train data

In [124]:
x_test=scaler.transform(x_test) #but we can directly transform our test data dont need to fit it first

In [125]:
x_train

array([[-1.        ,  2.64575131, -0.77459667,  0.26306757,  0.12381479],
       [ 1.        , -0.37796447, -0.77459667, -0.25350148,  0.46175632],
       [-1.        , -0.37796447,  1.29099445, -1.97539832, -1.53093341],
       [-1.        , -0.37796447,  1.29099445,  0.05261351, -1.11141978],
       [ 1.        , -0.37796447, -0.77459667,  1.64058505,  1.7202972 ],
       [-1.        , -0.37796447,  1.29099445, -0.0813118 , -0.16751412],
       [ 1.        , -0.37796447, -0.77459667,  0.95182631,  0.98614835],
       [ 1.        , -0.37796447, -0.77459667, -0.59788085, -0.48214934]])

In [126]:
x_test

array([[-1.        ,  2.64575131, -0.77459667, -1.45882927, -0.90166297],
       [-1.        ,  2.64575131, -0.77459667,  1.98496442,  2.13981082]])