In [2]:
#import pandas and numpy
import pandas as pd 

import numpy as np

In [3]:
#taking any random paragraph as our data and will train model to predict next word in it 

data="""A lion was once sleeping in the jungle when a mouse started running up and down his body just for fun. This disturbed the lion’s sleep, and he woke up quite angry. He was about to eat the mouse when the mouse desperately requested the lion to set him free. “I promise you, I will be of great help to you someday if you save me.” The lion laughed at the mouse’s confidence and let him go.

One day, a few hunters came into the forest and took the lion with them. They tied him up against a tree. The lion was struggling to get out and started to whimper. Soon, the mouse walked past and noticed the lion in trouble. Quickly, he ran and gnawed on the ropes to set the lion free. Both of them sped off into the jungle."""

In [4]:
#import nltk for working with text data 
import nltk


In [5]:
#seperate each sentence in paragrath
sentences=nltk.sent_tokenize(data)

In [6]:
len(sentences)

10

In [7]:
from keras.preprocessing.text import Tokenizer

Using TensorFlow backend.


In [8]:
tokenizer=Tokenizer()

In [9]:
tokenizer.fit_on_texts(sentences)

In [15]:
#convert text into sequences of numbers
encoded=tokenizer.texts_to_sequences([data])[0]

In [16]:
encoded

[5,
 2,
 7,
 21,
 22,
 12,
 1,
 13,
 14,
 5,
 6,
 15,
 23,
 8,
 3,
 24,
 25,
 26,
 27,
 28,
 29,
 30,
 31,
 1,
 32,
 33,
 3,
 9,
 34,
 8,
 35,
 36,
 9,
 7,
 37,
 4,
 38,
 1,
 6,
 14,
 1,
 6,
 39,
 40,
 1,
 2,
 4,
 16,
 10,
 17,
 41,
 42,
 11,
 43,
 44,
 45,
 18,
 46,
 47,
 4,
 11,
 48,
 49,
 11,
 50,
 51,
 52,
 1,
 2,
 53,
 54,
 1,
 55,
 56,
 3,
 57,
 10,
 58,
 59,
 60,
 5,
 61,
 62,
 63,
 19,
 1,
 64,
 3,
 65,
 1,
 2,
 66,
 20,
 67,
 68,
 10,
 8,
 69,
 5,
 70,
 1,
 2,
 7,
 71,
 4,
 72,
 73,
 3,
 15,
 4,
 74,
 75,
 1,
 6,
 76,
 77,
 3,
 78,
 1,
 2,
 12,
 79,
 80,
 9,
 81,
 3,
 82,
 83,
 1,
 84,
 4,
 16,
 1,
 2,
 17,
 85,
 18,
 20,
 86,
 87,
 19,
 1,
 13]

In [12]:
len(encoded)

143

In [26]:
#define total vocabulary size
vocab_size=len(tokenizer.word_index)+1

In [27]:
vocab_size

112

In [28]:
#create seperate lists of 4 sequences since we will use three of them as input and last one as output
sequences=[]
for i in range(len(encoded)-3):
    sequences.append(encoded[i:i+4])

In [29]:
sequences

[[5, 20, 29, 47],
 [20, 29, 47, 48],
 [29, 47, 48, 36],
 [47, 48, 36, 14],
 [48, 36, 14, 37],
 [36, 14, 37, 38],
 [14, 37, 38, 5],
 [37, 38, 5, 26],
 [38, 5, 26, 39],
 [5, 26, 39, 49],
 [26, 39, 49, 30],
 [39, 49, 30, 21],
 [49, 30, 21, 50],
 [30, 21, 50, 51],
 [21, 50, 51, 52],
 [50, 51, 52, 53],
 [51, 52, 53, 54],
 [52, 53, 54, 55],
 [53, 54, 55, 56],
 [54, 55, 56, 57],
 [55, 56, 57, 14],
 [56, 57, 14, 58],
 [57, 14, 58, 59],
 [14, 58, 59, 21],
 [58, 59, 21, 31],
 [59, 21, 31, 60],
 [21, 31, 60, 30],
 [31, 60, 30, 61],
 [60, 30, 61, 62],
 [30, 61, 62, 31],
 [61, 62, 31, 29],
 [62, 31, 29, 63],
 [31, 29, 63, 24],
 [29, 63, 24, 64],
 [63, 24, 64, 14],
 [24, 64, 14, 26],
 [64, 14, 26, 38],
 [14, 26, 38, 14],
 [26, 38, 14, 26],
 [38, 14, 26, 65],
 [14, 26, 65, 66],
 [26, 65, 66, 14],
 [65, 66, 14, 20],
 [66, 14, 20, 24],
 [14, 20, 24, 40],
 [20, 24, 40, 32],
 [24, 40, 32, 41],
 [40, 32, 41, 67],
 [32, 41, 67, 68],
 [41, 67, 68, 33],
 [67, 68, 33, 6],
 [68, 33, 6, 69],
 [33, 6, 69, 70],
 

In [30]:
#create dependent and independent variable

x=[]
y=[]
for i in range(len(sequences)):
    x.append(sequences[i][0:3])
    y.append(sequences[i][3])

In [37]:
#convert list to an array
x=np.array(x)
y=np.array(y)

In [62]:
x[0]

array([ 5, 20, 29])

In [64]:
np.array([5,20,29])

array([ 5, 20, 29])

In [32]:
y

[47,
 48,
 36,
 14,
 37,
 38,
 5,
 26,
 39,
 49,
 30,
 21,
 50,
 51,
 52,
 53,
 54,
 55,
 56,
 57,
 14,
 58,
 59,
 21,
 31,
 60,
 30,
 61,
 62,
 31,
 29,
 63,
 24,
 64,
 14,
 26,
 38,
 14,
 26,
 65,
 66,
 14,
 20,
 24,
 40,
 32,
 41,
 67,
 68,
 33,
 6,
 69,
 70,
 42,
 71,
 72,
 24,
 33,
 73,
 74,
 33,
 75,
 76,
 35,
 14,
 20,
 77,
 78,
 14,
 79,
 80,
 21,
 81,
 32,
 82,
 83,
 84,
 5,
 85,
 86,
 87,
 43,
 14,
 88,
 21,
 89,
 14,
 20,
 90,
 44,
 91,
 92,
 32,
 30,
 93,
 5,
 94,
 14,
 20,
 29,
 95,
 24,
 96,
 97,
 21,
 39,
 24,
 98,
 99,
 14,
 26,
 100,
 101,
 21,
 102,
 14,
 20,
 36,
 103,
 104,
 31,
 105,
 21,
 106,
 107,
 14,
 108,
 24,
 40,
 14,
 20,
 41,
 109,
 42,
 44,
 110,
 111,
 43,
 14,
 37]

In [48]:
from keras.utils import to_categorical

In [49]:
y=to_categorical(y,vocab_size)

In [50]:
y.shape

(140, 112)

In [150]:
#import libraries for model building
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import LSTM,Dense,Embedding

In [169]:
#start building model
model=Sequential()

In [170]:
#add Embedding layer
model.add(Embedding(input_dim=vocab_size,output_dim=10,input_length=3))

In [171]:
#add LSTM layer
model.add(LSTM(60))

In [172]:
#output layer
model.add(Dense(vocab_size,activation='softmax'))

In [173]:
#compile 
model.compile('adam',loss='categorical_crossentropy',metrics=['accuracy'])

In [174]:
#training model
model.fit(x,y,batch_size=1,epochs=50,validation_split=0.2)

Train on 112 samples, validate on 28 samples
Epoch 1/50
112/112 [==============================] - 2s 18ms/sample - loss: 4.7156 - acc: 0.0536 - val_loss: 4.6970 - val_acc: 0.1429
Epoch 2/50
112/112 [==============================] - 1s 4ms/sample - loss: 4.5158 - acc: 0.0982 - val_loss: 4.8508 - val_acc: 0.1429
Epoch 3/50
112/112 [==============================] - 1s 5ms/sample - loss: 4.2023 - acc: 0.0982 - val_loss: 5.0494 - val_acc: 0.1429
Epoch 4/50
112/112 [==============================] - 1s 5ms/sample - loss: 4.0779 - acc: 0.0982 - val_loss: 5.4952 - val_acc: 0.1429
Epoch 5/50
112/112 [==============================] - 1s 5ms/sample - loss: 3.9984 - acc: 0.0982 - val_loss: 5.5137 - val_acc: 0.1429
Epoch 6/50
112/112 [==============================] - 1s 5ms/sample - loss: 3.9299 - acc: 0.1071 - val_loss: 5.6663 - val_acc: 0.1429
Epoch 7/50
112/112 [==============================] - 1s 5ms/sample - loss: 3.8673 - acc: 0.1071 - val_loss: 5.9361 - val_acc: 0.1429
Epoch 8/50
112/1

In [175]:
np.array([  5,  20,  29]).reshape(1,3)

array([[ 5, 20, 29]])

In [176]:
np.argmax(model.predict(np.array([  5,  20,  29]).reshape(1,3)))

47

In [177]:
#testing function
def predict_next_word(model,tokenizer,text,n_words):
    result=''
    out_word=[]
    
    for i in range(n_words):
        input_data=text.split()
        encoded_data=[tokenizer.texts_to_sequences([x])[0] for x in input_data]
        encoded_data=np.array(encoded_data)
        encoded_data=encoded_data.reshape(1,3)
        

        output=np.argmax(model.predict(encoded_data))
        
        
        for index,word in tokenizer.word_index.items():
            if word==output:
                
                out_word.append(index)
                text=input_data[1]+" "+input_data[2]+" "+index
    result=' '.join(out_word)
    return result

In [178]:
#testing 
predict_next_word(model,tokenizer,"A lion was",4)

'once sleeping in the'

In [179]:
import pickle

In [183]:
#pickling model to load it in flask server
model.save("model.h5")

In [184]:
#pickling tokenizer object to use it in flask server later
pickle.dump(tokenizer,open("tokenizer.pkl",'wb'))